import csv

def export_to_csv(data, filename):
    fieldnames = [
        "Consignee address",
        "Consignee name",
        "Date of Invoice",
        "GST amount",
        "GST rate",
        "GST type",
        "GSTIN",
        "Item HSN code",
        "Last column to contain control totals for validation",
        "PO reference number",
        "State/ Address",
        "Supplier name",
        "Total amount"
    ]

    with open(filename, 'w', newline='') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        
        writer.writeheader()
        for item in data:
            writer.writerow(item)
data = [
    {
        "Consignee address ": "608, Mandi Kesar Ganj, Ludhiana (PB.)",
        "Consignee name": "SMARTPADE TECHNOLOGY PRIVATE LIMITED",
        "Date of Invoice": "23-Nov-22",
        "GST amount": "596.25",
        "GST rate": "18.00",
        "GST type": "IGST",
        "GSTIN": "06AAVC56045D124",
        "Item HSN code": "15079010",
        "Last column to contain control totals for validation": "12521.00",
        "PO reference number ": "MI09 dt. 12-Nov-22",
        "State/ Address": "Punjab",
        "Supplier name": "SMARTPADE TECHNOLOGY PRIVATE LIMITED",
        "Total amount": "12521.00"
    },
    {
        "Consignee address": "608 MANDI KESAR GANJ LUDHIANA -141001, Punjab, India",
        "Consignee name": "VARINDER JAIN",
        "Date of Invoice": "14/11/2022",
        "GST amount": "21376.94",
        "GST rate": "5%",
        "GST type": "CGST",
        "GSTIN": "03AAAPK5233K1ZX",
        "Item HSN code": "1507010",
        "Last column to contain control totals for validation": "21376.94",
        "PO reference number": "PO/RM/22-23/00980",
        "State/ Address": "Punjab",
        "Supplier name": "CREMICA FOOD INDUSTRIES LTD.",
        "Total amount": "427528.80"
    },
    {
        "Consignee address ": "608, Mandi Kesar Ganj, Ludhiana (PB.)",
        "Consignee name": "BHAMNI TRANSPORT CO.",
        "Date of Invoice": "12-Nov-22",
        "GST amount": "2,085.00",
        "GST rate": "5%",
        "GST type": "IGST",
        "GSTIN": "03AAFCF343K1ZX",
        "Item HSN code": "1507910",
        "Last column to contain control totals for validation": "43,795.65",
        "PO reference number ": "56303 dt. 12-Nov-22",
        "State/ Address": "Punjab",
        "Supplier name": "SMARTPADTLE TECHNOLOGY PRIVATE LIMITED",
        "Total amount": "43,795.65"
    },
    {
        "Consignee address": "CREMICA FOOD INDUSTRIES LIMITED\nGSI NANDI, KEHAR GANJ, LUDHIANA, LUDHIANA\nPunjab, India",
        "Consignee name": "CREMICA FOOD INDUSTRIES LIMITED",
        "Date of Invoice": "31-10-2022",
        "GST amount": "445200.00",
        "GST rate": "5.00%",
        "GST type": "CGST",
        "GSTIN": "06AAAVC5045U1ZX",
        "Item HSN code": "15079010",
        "Last column to contain control totals for validation": "445200.00",
        "PO reference number": "PO/FY23/BZHA/05966",
        "State/ Address": "Punjab, India",
        "Supplier name": "MODERN IMPEX (INDIA)",
        "Total amount": "445200.00"
    },
    {
        "Consignee address ": "C/O. Future Techno Park, A/55-56-57, Agro Food Park, Mathura Industrial Area, RIICO, Jaipur, Rajasthan - 302030, India",
        "Consignee name": "Reliance Retail Limited",
        "Date of Invoice": "25-Nov-22",
        "GST amount": "467.16",
        "GST rate": "5%",
        "GST type": "IGST",
        "GSTIN": "08CGJPM100041",
        "Item HSN code": "170114",
        "Last column to contain control totals for validation": "9,343.20",
        "PO reference number ": "PO/FY23/BMZH/05747",
        "State/ Address": "Rajasthan",
        "Supplier name": "Super Shine Agro Foods Pvt Ltd",
        "Total amount": "9,810.36"
    },
    {
        "Consignee address ": "Khasra No 247 248 249/1\nKhasra No 247 248 249/1\nThane - 400701",
        "Consignee name": "SMARTPADDLE TECHNOLOGY PRIVATE LIMITED",
        "Date of Invoice": "02.11.2022",
        "GST amount": "366.63",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "27AAVC6560645120",
        "Item HSN code": "19019010",
        "Last column to contain control totals for validation": "375.00",
        "PO reference number ": "407497299",
        "State/ Address": "Maharashtra",
        "Supplier name": "Reliance Retail Limited",
        "Total amount": "2,400.00"
    },
    {
        "Consignee address ": "MUNDKA\nDELHI\n110041",
        "Consignee name": "SHREE SHYAM AGRO FOODS PVT LTD",
        "Date of Invoice": "2-Nov-22",
        "GST amount": "7,10,083.36",
        "GST rate": "5%",
        "GST type": "IGST",
        "GSTIN": "07AABCK7182L1ZR",
        "Item HSN code": "170114",
        "Last column to contain control totals for validation": "35,504.16",
        "PO reference number ": "07A63CB7118E21ZR",
        "State/ Address": "DELHI",
        "Supplier name": "SUPER SHINE AGRO FOODS PVT LTD",
        "Total amount": "35,504.16"
    },
    {
        "Consignee address": "Super Shine Agrofoods Private Limited\nG-55-56-57 Agro Food Park M I A Alwar,\nAlwar - 301030\nRajasthan, India",
        "Consignee name": "Super Shine Agrofoods Private Limited",
        "Date of Invoice": "01-11-2022",
        "GST amount": "7848.80",
        "GST rate": "5.00",
        "GST type": "CGST+SGST",
        "GSTIN": "09BGAP5444126E",
        "Item HSN code": "090310",
        "Last column to contain control totals for validation": "7848.80",
        "PO reference number": "PO/FY23/BMH/05751",
        "State/ Address": "Rajasthan, India",
        "Supplier name": "Bizongo Private Limited",
        "Total amount": "7848.80"
    },
    {
        "Consignee address ": "VILLAGE REHMODI, PO-BUDHPARA, PS-BHOJPUR, VA UDAIPURIA, PO-BHOWAS CHOMU DIST JAIPUR",
        "Consignee name": "RELIANCE RETAIL LTD CHOMU (RAJ)",
        "Date of Invoice": "6-DEC-2022",
        "GST amount": "89.78",
        "GST rate": "5%",
        "GST type": "IGST",
        "GSTIN": "08AAECB1718ZP",
        "Item HSN code": "170114",
        "Last column to contain control totals for validation": "1795.50",
        "PO reference number ": "4115978476476",
        "State/ Address": "RAJASTHAN",
        "Supplier name": "SUPER SHINE AGRO FOODS PVT LTD",
        "Total amount": "1885.28"
    },
    {
        "Consignee address ": "Central Warehouse Godown No.1A2A2B\n5A 5B Via Udaipur Po Bhopwas\nCHOMU\nRajasthan - 303807",
        "Consignee name": "Smart Hub Chomu RRL",
        "Date of Invoice": "17.11.2022",
        "GST amount": "599.00",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "08AAECK7118E7ZP",
        "Item HSN code": "09087718",
        "Last column to contain control totals for validation": "2,400.00",
        "PO reference number ": "407625738",
        "State/ Address": "Rajasthan - 303807",
        "Supplier name": "Smart Hub Chomu RRL",
        "Total amount": "3,000.00"
    },
    {
        "Consignee address ": "MATSYA INDUSTRIAL AREA, AJMER ROAD, PALI, RAJASTHAN",
        "Consignee name": "SHREE BALAJI AGRO FOOD",
        "Date of Invoice": "15-Nov-22",
        "GST amount": "1398.26",
        "GST rate": "5%",
        "GST type": "IGST",
        "GSTIN": "08AAACR864527G",
        "Item HSN code": "170114",
        "Last column to contain control totals for validation": "53,865.00",
        "PO reference number ": "RJ/GKG276",
        "State/ Address": "Rajasthan",
        "Supplier name": "SHREE SHYAM AGRO FOOD PVT LTD",
        "Total amount": "53,865.00"
    },
    {
        "Consignee address ": "RELIANCE RETAIL LIMITED\n55-56-57 AGRA FOOD PARK M.I.A ALWAR, ALWAR - 301030\nRAJASTHAN, INDIA",
        "Consignee name": "RELIANCE RETAIL LIMITED",
        "Date of Invoice": "15-11-2022",
        "GST amount": "301640.00",
        "GST rate": "5%",
        "GST type": "CGST",
        "GSTIN": "09AABPC5444L1ZE",
        "Item HSN code": "0904101518",
        "Last column to contain control totals for validation": "301640.00",
        "PO reference number ": "PO/FY23/BMH/06159",
        "State/ Address": "Rajasthan, India",
        "Supplier name": "SUPER SHINE AGROFOODS PRIVATE LIMITED",
        "Total amount": "301640.00"
    },
    {
        "Consignee address ": "15/18 AND 21, INDUSTRIAL ESTATE, MORIVLI MIDC, AMBERNATH, THANE - 421501, Maharashtra, India",
        "Consignee name": "APRN ENTERPRISES PRIVATE LIMITED",
        "Date of Invoice": "Dec 07, 2022",
        "GST amount": "2744.93",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "27AAACA48691ZP",
        "Item HSN code": "4909.00.10",
        "Last column to contain control totals for validation": "6549.32",
        "PO reference number ": "BZPO-20135-230747",
        "State/ Address": "Maharashtra",
        "Supplier name": "Smartpaddle Technology Private Limited",
        "Total amount": "32136.42"
    },
    {
        "Consignee address ": "15 16 & 17, MIDC Industrial Estate,Morivli, MIDC Road, Taluka- Bhiwandi, Dist- Thane, Maharashtra, Code - 421302",
        "Consignee name": "McCOY PHARMA PVT. LTD.",
        "Date of Invoice": "29-Nov-22",
        "GST amount": "107.00",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "27AAMCBM9972",
        "Item HSN code": "39269099",
        "Last column to contain control totals for validation": "7,00,777.24",
        "PO reference number ": "41501/MARD/23",
        "State/ Address": "Maharashtra, Code - 27",
        "Supplier name": "SMARTPALE TECHNOLOGIES PRIVATE LIMITED",
        "Total amount": "8,08,997.24"
    },
    {
        "Consignee address": "M/S. APIN ENTERPRISES PRIVATE LIMITED\nPLOT NO 512/534 Bhosari Pimpri, Pimpri Chinchwad, Maharashtra, 411018",
        "Consignee name": "APIN ENTERPRISES PRIVATE LIMITED",
        "Date of Invoice": "21-11-2022",
        "GST amount": "13257.30",
        "GST rate": "9.00%",
        "GST type": "CGST",
        "GSTIN": "27AAECA48949",
        "Item HSN code": "39204900",
        "Last column to contain control totals for validation": "25252.00",
        "PO reference number ": "PO/FY23/BMH/06333",
        "State/ Address": "Maharashtra, India",
        "Supplier name": "Mccoy Pharma Private Limited",
        "Total amount": "132573.00"
    },
    {
        "Consignee address": "Plot No. 11 East, Wardhaman Nagar, Nagpur",
        "Consignee name": "Roy Agro Products",
        "Date of Invoice": "26-Nov-22",
        "GST amount": "54,589.26",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "27AOCR65102E1Z1",
        "Item HSN code": "230410",
        "Last column to contain control totals for validation": "11,46,280.00",
        "PO reference number": "SAUDA/22-23/30",
        "State/ Address": "Maharashtra, Code: 27",
        "Supplier name": "S.A.G. Multitrade Pvt. Ltd.",
        "Total amount": "11,46,280.00"
    },
    {
        "Consignee address ": "SURFJI FEED MILL, VILLAGE-PO-HETAMPULE,SADASPUR, DIST-BHUBANESHWAR, KHURDA, ODISHA, PIN-751214, BHUBANESWAR",
        "Consignee name": "ROY AGROVETS PRIVATE LIMITED",
        "Date of Invoice": "25-11-2022",
        "GST amount": "496400.00",
        "GST rate": "5%",
        "GST type": "CGST",
        "GSTIN": "27AORPR9081E1Z1",
        "Item HSN code": "010010",
        "Last column to contain control totals for validation": "496400.00",
        "PO reference number ": "PO/FY23/BZKA/02095",
        "State/ Address": "Odisha",
        "Supplier name": "Kunal Agro Products",
        "Total amount": "496400.00"
    },
    {
        "Consignee address ": "90B, SEC-18 DELHI JAIPUR EXPY GURGAON HARYANA",
        "Consignee name": "Smartpaddle Technology Pvt.Ltd. Vijay",
        "Date of Invoice": "29-12-2022",
        "GST amount": "6.31",
        "GST rate": "18%",
        "GST type": "---",
        "GSTIN": "06AAVC56045D12A",
        "Item HSN code": "---",
        "Last column to contain control totals for validation": "---",
        "PO reference number ": "---",
        "State/ Address": "Haryana",
        "Supplier name": "Madhur Iron & Steel (I) Pvt. Ltd.",
        "Total amount": "41.38"
    },
    {
        "Consignee address ": "PLOT NO 121/3 1218121712/13, URALA ACHOLI MARG, KANHEERA, RAJUR, 492221, Chhattisgarh, India",
        "Consignee name": "VIJAY TRANSMISSION PRIVATE LIMITED",
        "Date of Invoice": "30/12/2022",
        "GST amount": "2244.00",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "22AAAVC4467B1ZO",
        "Item HSN code": "84829990",
        "Last column to contain control totals for validation": "3507.00",
        "PO reference number ": "VTP/PUR/662",
        "State/ Address": "Rajur",
        "Supplier name": "Smartpaddle Technology Private Limited",
        "Total amount": "2081185.4731"
    },
    {
        "Consignee address ": "SMARTPOLE TECHNOLOGY PRIVATE LIMITED\nPLOT NO.12/13, VIKAS NAGAR, NH-24,\nGURGAON, HARYANA - 122001",
        "Consignee name": "SMARTPOLE TECHNOLOGY PRIVATE LIMITED",
        "Date of Invoice": "23-12-2022",
        "GST amount": "30388.94",
        "GST rate": "18.0",
        "GST type": "CGST",
        "GSTIN": "06AAJCA6812D1Z6",
        "Item HSN code": "85369090",
        "Last column to contain control totals for validation": "20230886.06",
        "PO reference number ": "PO No. 18/22-23/1460",
        "State/ Address": "Haryana",
        "Supplier name": "Madhur Iron & Steel (I) Pvt. Ltd.",
        "Total amount": "20230886.06"
    },
    {
        "Consignee address ": "Madhur Iron & Steel (India) Private Limited\n11A Near Poly sond flyover\nChhattisgarh, India",
        "Consignee name": "Madhur Iron & Steel (India) Private Limited",
        "Date of Invoice": "26-12-2022",
        "GST amount": "399039.42",
        "GST rate": "18.00%",
        "GST type": "CGST",
        "GSTIN": "06AAVC5045D71R",
        "Item HSN code": "72162100",
        "Last column to contain control totals for validation": "399039.42",
        "PO reference number ": "PO/FY23/BZL/0737",
        "State/ Address": "Madhur Iron & Steel (India) Private Limited\n11A Near Poly sond flyover\nChhattisgarh, India",
        "Supplier name": "Sparkle Transmission Private Limited",
        "Total amount": "399039.42"
    },
    {
        "Consignee address": "M/S. ICONICS FASHION RETAILING PVT. LTD. \nSMART PADDLE TECHNOLOGY PVT LTD\n SECTOR 18, UDYOG VIHAR PHASE 2 - 151\nGURGAON\n122001",
        "Consignee name": "SMART PADDLE TECHNOLOGY PVT LTD",
        "Date of Invoice": "07-02-2023",
        "GST amount": "179.00",
        "GST rate": "18.00",
        "GST type": "CGST",
        "GSTIN": "06ACC5856L1ZA",
        "Item HSN code": "62044220",
        "Last column to contain control totals for validation": "1,279.00",
        "PO reference number": "PO/IC523/NO.-06/ACC4C856L1ZA",
        "State/ Address": "HARYANA / 12001",
        "Supplier name": "KHAIRA KNITS",
        "Total amount": "1,279.00"
    },
    {
        "Consignee address ": "NA",
        "Consignee name": "ICONIC FASHION RETAILING PRIVATE LIMITED",
        "Date of Invoice": "Feb 08, 2023",
        "GST amount": "326.06",
        "GST rate": "18.00",
        "GST type": "CGST",
        "GSTIN": "06AAGCC5695D124",
        "Item HSN code": "6105",
        "Last column to contain control totals for validation": "9718073381",
        "PO reference number ": "IC/PO/523/334",
        "State/ Address": "Haryana",
        "Supplier name": "Smartpaddle Technology Private Limited",
        "Total amount": "2548.00"
    },
    {
        "Consignee address": "SMARTPADDLE TECHNOLOGIES PVT LTD\nEXP, GURGAON\nSECTOR 18, UDYOG VIHAR PHASE 6 - 151\n122001",
        "Consignee name": "SMARTPADDLE TECHNOLOGIES PVT LTD",
        "Date of Invoice": "07-02-2023",
        "GST amount": "10955.28",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "06ACCCS8561L24",
        "Item HSN code": "62044200",
        "Last column to contain control totals for validation": "637311",
        "PO reference number": "PO/FY23/B2HA/08483",
        "State/ Address": "HARYANA / JAURAUSI",
        "Supplier name": "KHASRA NUMBER 512, OPPOSITE PLOT NO. - 151\nSECTOR 37, UDYOG VIHAR PHASE 6 - 122001",
        "Total amount": "637311"
    },
    {
        "Consignee address": "KHASRA NO.512 GOL,DELHI VILLAGE VIHAR PHASE NO-VI, SECTOR-23/B/W.S.H UDYOG VIHAR PHASE NO VI, Sector-23 Gurugram, Gurugram, Haryana, India",
        "Consignee name": "Weave And Knits",
        "Date of Invoice": "07-02-2023",
        "GST amount": "63731.94",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "06AAV45012ALR",
        "Item HSN code": "62045200",
        "Last column to contain control totals for validation": "63731.94",
        "PO reference number": "PO/FY23/BZH/08483",
        "State/ Address": "Haryana, India",
        "Supplier name": "Sparkle Fashions",
        "Total amount": "637310.94"
    },
    {
        "Consignee address": "B-379/5, Village-Nabi Sarai, P.O.- Sikri, Distt-Bharatpur, Rajasthan-321001(India)",
        "Consignee name": "Sampaat Aluminium Pvt Ltd",
        "Date of Invoice": "16/03/2023",
        "GST amount": "879.00",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "08AAECS5264Q1Z5",
        "Item HSN code": "761010",
        "Last column to contain control totals for validation": "54,929.00",
        "PO reference number": "P.O. No. : 12/03/2023",
        "State/ Address": "Rajasthan",
        "Supplier name": "Anll Metals",
        "Total amount": "54,929.00"
    },
    {
        "Consignee address": "Sanket\n537/1, RAKANPURA, KALOL, Gandhinagar, Gujarat, India",
        "Consignee name": "Samrat Aluminium Private Limited",
        "Date of Invoice": "March 14, 2023",
        "GST amount": "248197.95",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "24AEE53524G1Z2",
        "Item HSN code": "76011010",
        "Last column to contain control totals for validation": "248197.95",
        "PO reference number": "sap/nl/mar",
        "State/ Address": "Gujarat",
        "Supplier name": "Bizongo HK",
        "Total amount": "1378877.50"
    },
    {
        "Consignee address": "286, Vijay Industrial Estate, 8th, Bhilukhu Gruh, Odhav, Ahmedabad, 382 415 (Gujarat)",
        "Consignee name": "Samprat Aluminium Pvt Ltd",
        "Date of Invoice": "12/03/2023",
        "GST amount": "252909.00",
        "GST rate": "18.00",
        "GST type": "CGST",
        "GSTIN": "24AABCS5645D1ZL",
        "Item HSN code": "760110",
        "Last column to contain control totals for validation": "1,657,959.00",
        "PO reference number": "PON/PY/23/6/0948",
        "State/ Address": "Gujarat",
        "Supplier name": "Ankit Metals",
        "Total amount": "1,405,050.00"
    },
    {
        "Consignee address": "SAMAPT ALUMINIUM PRIVATE LIMITED\nS. 286 NR BHUSHUK GRUH CHOKDI AHMEDABAD Ahmedabad\nGujarat, 382415",
        "Consignee name": "SAMAPT ALUMINIUM PRIVATE LIMITED",
        "Date of Invoice": "11-03-2023",
        "GST amount": "145730.00",
        "GST rate": "18.00%",
        "GST type": "CGST",
        "GSTIN": "27AAXCS5242L1Z",
        "Item HSN code": "76051010",
        "Last column to contain control totals for validation": "1457300.00",
        "PO reference number": "PO/FY23/BM/09448",
        "State/ Address": "Gujarat, India",
        "Supplier name": "BIZONGLE TECHNOLOGY PRIVATE LIMITED",
        "Total amount": "1457300.00"
    },
    {
        "Consignee address ": "Bizongo HQ, 3rd Floor, Off. Sakhi Vihar Road, Sakhi Naka, Andheri East, Mumbai - 400072, Maharashtra, India",
        "Consignee name": "Bizongo",
        "Date of Invoice": "Apr 11, 2023",
        "GST amount": "274.95",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "27AAYCCF7000N1ZI",
        "Item HSN code": "090910",
        "Last column to contain control totals for validation": "1375408.88",
        "PO reference number ": "GSPMH24/000082",
        "State/ Address": "Karnataka, India",
        "Supplier name": "Smartpaddle Technology Private Limited",
        "Total amount": "1375408.88"
    },
    {
        "Consignee address ": "C/o. P.P. Ware House, 3rd Floor, Opp Himalaya Drug Co. Banglore-560132 State Name: Maharashtra, Code: 27",
        "Consignee name": "M/s. V.N. Traders",
        "Date of Invoice": "06-APR-2023",
        "GST amount": "6306.87",
        "GST rate": "5%",
        "GST type": "CGST",
        "GSTIN": "29AAACM7094F1Z9",
        "Item HSN code": "090312",
        "Last column to contain control totals for validation": "11,467.20",
        "PO reference number ": "GJ-18-BT-2326",
        "State/ Address": "Karnataka",
        "Supplier name": "MRF AgroTech Industries",
        "Total amount": "1,32,440.00"
    },
    {
        "Consignee address ": "SMARTMADE TECHNOLOGY PRIVATE LIMITED\nBinzonia House, 3rd Floor, Off Saki Vihar Road, Sakinaka,\nAndheri East, Mumbai - 400072",
        "Consignee name": "SMARTMADE TECHNOLOGY PRIVATE LIMITED",
        "Date of Invoice": "04-04-2023",
        "GST amount": "124056.60",
        "GST rate": "5.0000",
        "GST type": "CGST",
        "GSTIN": "09BVKPC45212B",
        "Item HSN code": "09109990",
        "Last column to contain control totals for validation": "138310.20",
        "PO reference number ": "BZ-SKU-0186675",
        "State/ Address": "Maharashtra",
        "Supplier name": "FOOD SERVICE (INDIA) PRIVATE LIMITED",
        "Total amount": "138310.20"
    },
    {
        "Consignee address ": "Bizongo HQ, Krislon House, 3rd Floor, Off. Saki Vihar Road, Saki Naka, Andheri East, Mumbai - 400072, Maharashtra, India",
        "Consignee name": "Bizongo",
        "Date of Invoice": "Apr 05, 2023",
        "GST amount": "2744.94",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "27AAECT8265F1Z4",
        "Item HSN code": "630220",
        "Last column to contain control totals for validation": "6805.0",
        "PO reference number ": "TEPL/23-24/07",
        "State/ Address": "Maharashtra",
        "Supplier name": "TRISA EXPORTS PRIVATE LIMITED",
        "Total amount": "1616255.55"
    },
    {
        "Consignee address": "Bizongo HK Krislon House, 3rd Floor, Off Sakki Sakki Naka, Andheri East, Mumbai - 400072",
        "Consignee name": "SMARTPADDLE TECHNOLOGY PRIVATE LIMITED",
        "Date of Invoice": "23-24-10",
        "GST amount": "74427.50",
        "GST rate": "2.5%",
        "GST type": "CGST",
        "GSTIN": "27AAVC56405D120",
        "Item HSN code": "52081990",
        "Last column to contain control totals for validation": "157195.55",
        "PO reference number": "PO/24/MH/48",
        "State/ Address": "Maharashtra, Code: 27",
        "Supplier name": "Vinayak Enterprises",
        "Total amount": "60805.00"
    },
    {
        "Consignee address": "BUILDING NO EZ GLA NO 101 102 KALHER ROAD, BHIWANDI THANE Thane, 421302",
        "Consignee name": "VINAYAK ENTERPRISES",
        "Date of Invoice": "05-04-2023",
        "GST amount": "1571955.00",
        "GST rate": "2.50%",
        "GST type": "CGST",
        "GSTIN": "27AAEVC5678124",
        "Item HSN code": "630291",
        "Last column to contain control totals for validation": "1571955.00",
        "PO reference number": "PO/24/MH/48",
        "State/ Address": "Maharashtra, India",
        "Supplier name": "BIZONGLE TECHNOLOGY PRIVATE LIMITED",
        "Total amount": "1571955.00"
    },
    {
        "Consignee address ": "Plot No. 3 Plot No. 6, 38-39, 2nd Floor, Red Flag Business Park, Ahmednagar - 411002",
        "Consignee name": "Komal Worldwide Private Limited",
        "Date of Invoice": "21-Apr-23",
        "GST amount": "303.65",
        "GST rate": "5%",
        "GST type": "---",
        "GSTIN": "27CDFAB716E6B64C91",
        "Item HSN code": "62113000",
        "Last column to contain control totals for validation": "---",
        "PO reference number ": "---",
        "State/ Address": "Maharashtra",
        "Supplier name": "SMARTPADE TECHNOLOGY PRIVATE LIMITED",
        "Total amount": "6377.00"
    },
    {
        "Consignee address ": "ABC Company, 123 Main Street, Mumbai, Maharashtra 400001",
        "Consignee name": "ABC Company",
        "Date of Invoice": "15/03/2023",
        "GST amount": "100",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "0123456789",
        "Item HSN code": "123456",
        "Last column to contain control totals for validation": "1000",
        "PO reference number ": "1234567890",
        "State/ Address": "Maharashtra",
        "Supplier name": "XYZ Company",
        "Total amount": "1100"
    },
    {
        "Consignee address": "SMARTDOLE TECHNOLOGY PRIVATE LIMITED\nSurvey No. 6, A/s, Muddebihal Road, Bellary, Karnataka, 583102",
        "Consignee name": "SMARTDOLE TECHNOLOGY PRIVATE LIMITED",
        "Date of Invoice": "29-03-2023",
        "GST amount": "17887.22",
        "GST rate": "5.00",
        "GST type": "CGST",
        "GSTIN": "29AAJCK5525F1Z6",
        "Item HSN code": "62113300",
        "Last column to contain control totals for validation": "31254.58",
        "PO reference number": "PO/FY23/BZKA/03157",
        "State/ Address": "Karnataka",
        "Supplier name": "RONAL FASHIONS",
        "Total amount": "178877.22"
    },
    {
        "Consignee address ": "H.No. 706/A, 2nd Floor, Opp. Sai Geetha Ashram, Tumkunta, Hyderabad",
        "Consignee name": "ONE COMMERCE LIMITED",
        "Date of Invoice": "6-Apr-23",
        "GST amount": "8,228.38",
        "GST rate": "5%",
        "GST type": "---",
        "GSTIN": "36AACKC3587D",
        "Item HSN code": "27101390",
        "Last column to contain control totals for validation": "271",
        "PO reference number ": "PO/FY23/BZKA/03157",
        "State/ Address": "TELANGANA",
        "Supplier name": "Komal Worldwide Private Limited",
        "Total amount": "1,72,807.00"
    },
    {
        "Consignee address ": "Sector 18, 90B, Delhi - Jaipur Exp Gurgaon - 122001, Haryana, India",
        "Consignee name": "Smartpaddle Technology Private Limited",
        "Date of Invoice": "Apr 11, 2023",
        "GST amount": "272.49",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "06AAVC56045D124",
        "Item HSN code": "NA",
        "Last column to contain control totals for validation": "3183.01",
        "PO reference number ": "PO/48/23-24",
        "State/ Address": "Haryana",
        "Supplier name": "AK Industries",
        "Total amount": "2724.85"
    },
    {
        "Consignee address ": "KHASRA NO. 84/11/2,13,14,15,16,17 VILLAGE AKBARPUR, BAROTA, PIN 131301",
        "Consignee name": "A.K. INDUSTRIES",
        "Date of Invoice": "10-04-2023",
        "GST amount": "2,003.58",
        "GST rate": "9.00%",
        "GST type": "CGST",
        "GSTIN": "06AGF5896D124",
        "Item HSN code": "72201110",
        "Last column to contain control totals for validation": "26,269.20",
        "PO reference number ": "EDZHR/23-24/38",
        "State/ Address": "Haryana",
        "Supplier name": "Edzino Digitech Pvt. Ltd. (HR)",
        "Total amount": "26,269.20"
    },
    {
        "Consignee address": "Sector 60, HSIIDC, Faridabad, Haryana, India",
        "Consignee name": "Edino Digitech Private Limited",
        "Date of Invoice": "10-04-2023",
        "GST amount": "2626.99",
        "GST rate": "9.00%",
        "GST type": "CGST",
        "GSTIN": "06AAECS9576N1Z5",
        "Item HSN code": "72201100",
        "Last column to contain control totals for validation": "26269.99",
        "PO reference number": "PO/24/HA/122",
        "State/ Address": "Haryana, India",
        "Supplier name": "A K Industries",
        "Total amount": "26269.99"
    },
    {
        "Consignee address ": "63/108, Delhi - Jaipur Expy Gurgaon - 122001, Haryana, India",
        "Consignee name": "Smartpaddle Technology Private Limited",
        "Date of Invoice": "April 13, 2023",
        "GST amount": "226.40",
        "GST rate": "5.0%",
        "GST type": "IGST",
        "GSTIN": "06AABCS4504L1ZA",
        "Item HSN code": "52083230",
        "Last column to contain control totals for validation": "4671.40",
        "PO reference number ": "PO/0001/23-24",
        "State/ Address": "Haryana",
        "Supplier name": "SHREYANS CREATION GLOBAL LIMITED",
        "Total amount": "4499.80"
    },
    {
        "Consignee address ": "19A, CANAL SOUTH ROAD, KOLKATA - 700 015",
        "Consignee name": "SHREYANS CREATION GLOBAL LTD",
        "Date of Invoice": "11-APR-23",
        "GST amount": "21,403.01",
        "GST rate": "5%",
        "GST type": "IGST",
        "GSTIN": "19AAJCS4574R1ZA",
        "Item HSN code": "5208230",
        "Last column to contain control totals for validation": "4,28,060.16",
        "PO reference number ": "PO/24/HA/171",
        "State/ Address": "WEST BENGAL, CODE : 19",
        "Supplier name": "SMARTPADDLE TECHNOLOGY PRIVATE LIMITED",
        "Total amount": "4,49,463.17"
    },
    {
        "Consignee address": "4TH FLOOR, S-50, B- Block, C.N. ROAD, KOLKATA, Kolkata, 700015",
        "Consignee name": "SIDHARTH TEXCON PRIVATE LIMITED",
        "Date of Invoice": "20-24-2023",
        "GST amount": "31922.10",
        "GST rate": "5.00",
        "GST type": "CGST",
        "GSTIN": "19AAECS1302012G",
        "Item HSN code": "52082320",
        "Last column to contain control totals for validation": "31922.10",
        "PO reference number ": "PO/24/HA/171",
        "State/ Address": "West Bengal, India",
        "Supplier name": "SHREYANS CREATION GLOBAL LIMITED",
        "Total amount": "3192210.00"
    },
    {
        "Consignee address ": "VILL- UMBERGAON, TA-VALSAD, DIST-VALSAD, STATE-GUJARAT, PIN-396171",
        "Consignee name": "RJ TUBES PVT LTD",
        "Date of Invoice": "24-Apr-23",
        "GST amount": "6,62,582.43",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "24AAICT8058F1Z6",
        "Item HSN code": "74040012",
        "Last column to contain control totals for validation": "36,81,013.50",
        "PO reference number ": "PO/24/GJ/15",
        "State/ Address": "Gujarat",
        "Supplier name": "Esse Trading IMP LLP",
        "Total amount": "43,43,595.93"
    },
    {
        "Consignee address": "SHOP NO 353 CRYSTAL POINT MALL ABOVE STAR BAZAR LINK ROAD ANDHERI WEST MUMBAI MAHARASHTRA - 400053",
        "Consignee name": "RJ TUBES PRIVATE LIMITED",
        "Date of Invoice": "24-04-2023",
        "GST amount": "1416402.50",
        "GST rate": "18.00",
        "GST type": "CGST",
        "GSTIN": "27BYKPM6848N1Z6",
        "Item HSN code": "74040012",
        "Last column to contain control totals for validation": "2979795.00",
        "PO reference number": "PO/24/GJ/15",
        "State/ Address": "Maharashtra, India",
        "Supplier name": "ESSE TRADING IMPEX LLP",
        "Total amount": "4396237.50"
    },
    {
        "Consignee address": "RIHU TUBES PRIVATE LIMITED\nGIDC, Phase 2, Dared,\nAmboli, Botad, Gujarat - 364210",
        "Consignee name": "RIHU TUBES PRIVATE LIMITED",
        "Date of Invoice": "25-APR-2023",
        "GST amount": "1855.99",
        "GST rate": "18.00",
        "GST type": "CGST",
        "GSTIN": "24AAFCJ85041L1Z",
        "Item HSN code": "74040190",
        "Last column to contain control totals for validation": "24.61.00",
        "PO reference number": "22ALAPF353002K",
        "State/ Address": "Gujarat",
        "Supplier name": "JANMANAGAR TRANSPORT",
        "Total amount": "24261.00"
    },
    {
        "Consignee address ": "MENTON SWITCHGEARS PVT LTD\nNo.7, SIPCOT Industrial Complex,\nPhase-II, Perungudi, Chennai - 600 096",
        "Consignee name": "MENTON SWITCHGEARS PVT LTD",
        "Date of Invoice": "25-Apr-2023",
        "GST amount": "14,849.00",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "33AAACM6361D1Z5",
        "Item HSN code": "85369090",
        "Last column to contain control totals for validation": "4,21,899.00",
        "PO reference number ": "16994",
        "State/ Address": "Tamil Nadu",
        "Supplier name": "MERTON SWITCHGEARS PVT LTD",
        "Total amount": "2,51,199.00"
    },
    {
        "Consignee address ": "SMARTNODE TECHNOLOGIES PRIVATE LIMITED\nRAILWAY STATION, MEDAK DISTRICT\n502311, India",
        "Consignee name": "SMARTNODE TECHNOLOGIES PRIVATE LIMITED",
        "Date of Invoice": "29-04-2023",
        "GST amount": "12779.29",
        "GST rate": "18.00",
        "GST type": "CGST",
        "GSTIN": "36AABCS7098C1Z9",
        "Item HSN code": "85444990",
        "Last column to contain control totals for validation": "171485.00",
        "PO reference number ": "PO/22M4H545",
        "State/ Address": "Telangana",
        "Supplier name": "RPP INFRA",
        "Total amount": "171485.00"
    },
    {
        "Consignee address": "B-36/606/120, RAILWAY STATION, MODAKBHAJI PALYAM, NEAR SIVA TEMPLE, VISHAKAPATNAM, ANDHRA PRADESH, 530003, India",
        "Consignee name": "VAIRAV INFRA",
        "Date of Invoice": "Apr 30, 2023",
        "GST amount": "1548.93",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "36CGNPM1201D1ZO",
        "Item HSN code": "85444990",
        "Last column to contain control totals for validation": "15548.93",
        "PO reference number": "GPMHW240001816",
        "State/ Address": "Andhra Pradesh",
        "Supplier name": "Smartpaddle Technology Private Limited",
        "Total amount": "8640.07"
    },
    {
        "Consignee address ": "M/s. JINDAL SAW LTD.",
        "Consignee name": "JINDAL SAW LTD.",
        "Date of Invoice": "08/03/2023",
        "GST amount": "5,67,891.00",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "06AAACJ3161F1Z1",
        "Item HSN code": "72089090",
        "Last column to contain control totals for validation": "11,35,782.00",
        "PO reference number ": "1000061438",
        "State/ Address": "Haryana",
        "Supplier name": "INDIAN AGRO  INDUSTRIES LIMITED",
        "Total amount": "11,35,782.00"
    },
    {
        "Consignee address ": "M/s. JINDAL SAW LTD.",
        "Consignee name": "JINDAL SAW LTD.",
        "Date of Invoice": "08/03/2023",
        "GST amount": "5,67,891.00",
        "GST rate": "18%",
        "GST type": "SGST",
        "GSTIN": "06AAACJ3161F1Z1",
        "Item HSN code": "72089090",
        "Last column to contain control totals for validation": "11,35,782.00",
        "PO reference number ": "1000061438",
        "State/ Address": "Haryana",
        "Supplier name": "INDIAN AGRO  INDUSTRIES LIMITED",
        "Total amount": "11,35,782.00"
    },
    {
        "Consignee address ": "M/s. JINDAL SAW LTD.",
        "Consignee name": "JINDAL SAW LTD.",
        "Date of Invoice": "08/03/2023",
        "GST amount": "11,35,782.00",
        "GST rate": "18%",
        "GST type": "IGST",
        "GSTIN": "06AAACJ3161F1Z1",
        "Item HSN code": "72089090",
        "Last column to contain control totals for validation": "22,71,564.00",
        "PO reference number ": "1000061438",
        "State/ Address": "Haryana",
        "Supplier name": "INDIAN AGRO  INDUSTRIES LIMITED",
        "Total amount": "22,71,564.00"
    },
    {
        "Consignee address": "M/S. AGRIYA AGRO TECH INDUSTRIES, AT - 45 MAKARAIYA UNJHA MAHESANA, MEHSANA - 382 705, GUJARAT, INDIA",
        "Consignee name": "M/S. AGRIYA AGRO TECH INDUSTRIES",
        "Date of Invoice": "03-05-2023",
        "GST amount": "374371.20",
        "GST rate": "5.00%",
        "GST type": "CGST",
        "GSTIN": "24AANYM1435D1ZB",
        "Item HSN code": "09032000",
        "Last column to contain control totals for validation": "374371.20",
        "PO reference number": "PO/24/MH/618",
        "State/ Address": "GUJARAT",
        "Supplier name": "SMARTPADLE TECHNOLOGY PRIVATE LIMITED",
        "Total amount": "374371.20"
    },
    {
        "Consignee address ": "Bizongo HQ, Krislon House, 3rd Floor, Off. Saki Vihar Road, Saki Naka, Andheri East, Mumbai - 400072, Maharashtra, India",
        "Consignee name": "Bizongo",
        "Date of Invoice": "May 05, 2023",
        "GST amount": "358.46",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "27AABCS6845D120",
        "Item HSN code": "21069091",
        "Last column to contain control totals for validation": "720.0",
        "PO reference number ": "GSPMH/24/002098",
        "State/ Address": "West Bengal",
        "Supplier name": "Smartpaddle Technology Private Limited",
        "Total amount": "3887.88"
    },
    {
        "Consignee address": "Plot No. 6, Chhatra Marg, Udyog Vihar, Phase - 4, Gurugram, Haryana - 122001",
        "Consignee name": "Flockfabs India (India) LLP",
        "Date of Invoice": "2-Jun-2023",
        "GST amount": "2,50,250.00",
        "GST rate": "18.00",
        "GST type": "CGST",
        "GSTIN": "09AAMFF0002DJZ",
        "Item HSN code": "60064910",
        "Last column to contain control totals for validation": "1,44,270.00",
        "PO reference number ": "23-CS-372",
        "State/ Address": "Haryana",
        "Supplier name": "Smartpaddle Technology Pvt. Ltd.",
        "Total amount": "8,00,000.00"
    },
    {
        "Consignee address": "FLOCK FABS INDIA\nBEHRAMPUR ROAD FLOCK FABS\nINDUSTRIAL VILLAGE KHANDSA 38TH MILE STONE,\nGURGAON,\n122001",
        "Consignee name": "FLOCK FABS INDIA",
        "Date of Invoice": "27-05-2023",
        "GST amount": "21640.00",
        "GST rate": "5.00",
        "GST type": "CGST",
        "GSTIN": "06AAXCS37752E",
        "Item HSN code": "580210",
        "Last column to contain control totals for validation": "21640.00",
        "PO reference number": "PO/24/HA/1090",
        "State/ Address": "Haryana, India",
        "Supplier name": "JAIN CORD INDUSTRIES PRIVATE LIMITED",
        "Total amount": "21640.00"
    },
    {
        "Consignee address": "VILLAGE DAUTANA, CHANDORI ROAD, TEHSIL CHHATA, MATHURA - 281 401, Uttar Pradesh, India",
        "Consignee name": "AARAV SHARMA",
        "Date of Invoice": "03/06/2023",
        "GST amount": "1487.74",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "09AAACJ775126",
        "Item HSN code": "63061090",
        "Last column to contain control totals for validation": "800.00",
        "PO reference number": "GSPHA24/0003316",
        "State/ Address": "Uttar Pradesh",
        "Supplier name": "BIZ ONGO",
        "Total amount": "14877.42"
    },
    {
        "Consignee address ": "Regd. Office Plot No. 991/1-106/pablik,\nSur No. 96/991-1, Opp. Sunam Steel,\nBehramura,\nAhmedabad",
        "Consignee name": "VAX FASHION PRIVATE LIMITED",
        "Date of Invoice": "26-06-2023",
        "GST amount": "19,661.93",
        "GST rate": "5%",
        "GST type": "IGST",
        "GSTIN": "24AAACH7986E1Z7",
        "Item HSN code": "52083270",
        "Last column to contain control totals for validation": "2,387.00 Meters",
        "PO reference number ": "PO/24/M-16865",
        "State/ Address": "Gujarat",
        "Supplier name": "Smartpaddle Technology Pvt. Ltd.",
        "Total amount": "3,93,238.55"
    },
    {
        "Consignee address ": "SMART FASHIONS PVT LTD\n1st Floor, 36, Mittal Court,\nNariman Point\nMumbai-400021",
        "Consignee name": "SMART FASHIONS PVT LTD",
        "Date of Invoice": "24-06-2023",
        "GST amount": "15289.84",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "27AABCS7081F1Z6",
        "Item HSN code": "62034290",
        "Last column to contain control totals for validation": "115123.14",
        "PO reference number ": "PO/23/1565",
        "State/ Address": "Maharashtra",
        "Supplier name": "V.V.S FASHIONS PVT. LTD.",
        "Total amount": "85132.14"
    },
    {
        "Consignee address ": "90B, Sector 18, Delhi - Jaipur Expy, Village AKBARPUR, Bahadur Garh",
        "Consignee name": "A.K INDUSTRIES",
        "Date of Invoice": "03-07-2023",
        "GST amount": "4073.58",
        "GST rate": "9.00%",
        "GST type": "CGST",
        "GSTIN": "06AAGFS896124",
        "Item HSN code": "72091730",
        "Last column to contain control totals for validation": "53,409.16",
        "PO reference number ": "PO/24/HA/1844",
        "State/ Address": "Haryana (06)",
        "Supplier name": "Edzin Digitech Pvt. Ltd. (HR)",
        "Total amount": "45,262.00"
    },
    {
        "Consignee address ": "PLOT NO 58, PANAJPORE VILLAGE, MURHALI, KUNDLI, MURTHAL - 131029, Haryana, India",
        "Consignee name": "AK Industries",
        "Date of Invoice": "01-07-2023",
        "GST amount": "53409.16",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "06AAGF6R5695B2E1",
        "Item HSN code": "72091730",
        "Last column to contain control totals for validation": "53409.16",
        "PO reference number ": "PO/24/HA/1844",
        "State/ Address": "Haryana, India",
        "Supplier name": "Edino Digitech Private Limited",
        "Total amount": "53409.16"
    },
    {
        "Consignee address ": "Sector 18, 90B, Delhi - Jaipur Expy Gurgaon 122001 Haryana India",
        "Consignee name": "Smartpaddle Technology Private Limited",
        "Date of Invoice": "2023-07-03",
        "GST amount": "55399.8200",
        "GST rate": "18.00",
        "GST type": "CGST",
        "GSTIN": "06AGFA5896G1ZE",
        "Item HSN code": "---",
        "Last column to contain control totals for validation": "---",
        "PO reference number ": "PO/496/23-24",
        "State/ Address": "Haryana",
        "Supplier name": "A K INDUSTRIES",
        "Total amount": "355399.82"
    },

    {
        "Consignee address ": "Sector 18, Udyog Vihar, Phase 4, Gurugram, Haryana, India",
        "Consignee name": "Smartpaddle Technologies Private Limited",
        "Date of Invoice": "03-08-2023",
        "GST amount": "31950.00",
        "GST rate": "18.00",
        "GST type": "CGST",
        "GSTIN": "07AAUCC7250B1Z",
        "Item HSN code": "85076000",
        "Last column to contain control totals for validation": "2094500.00",
        "PO reference number ": "PO/24/HA/2391",
        "State/ Address": "Haryana, India",
        "Supplier name": "Cellcor Gadgets Limited",
        "Total amount": "2094500.00"
    },
    {
        "Consignee address ": "Sector 18, 90B, Delhi - Jaipur Expy Gurgaon 122001 Haryana India",
        "Consignee name": "Smartpaddle Technology Private Limited",
        "Date of Invoice": "2023-08-03",
        "GST amount": "2500.00",
        "GST rate": "12.00",
        "GST type": "CGST",
        "GSTIN": "07AACLU7506G1Z8",
        "Item HSN code": "---",
        "Last column to contain control totals for validation": "---",
        "PO reference number ": "B2P0-2127-259719",
        "State/ Address": "Haryana",
        "Supplier name": "CELLCOR GADGETS LIMITED",
        "Total amount": "215025.00"
    },
    {
        "Consignee address ": "57, Astha Industrial Estate, B.H. Patel Marg, Narol, Ahmedabad, Gujarat, 382440",
        "Consignee name": "Kalairadhani Trendz Ltd",
        "Date of Invoice": "8-Aug-23",
        "GST amount": "1,527.10",
        "GST rate": "5%",
        "GST type": "---",
        "GSTIN": "24AAGH5871AR2ZD",
        "Item HSN code": "52081130",
        "Last column to contain control totals for validation": "33,562.00",
        "PO reference number ": "PO/24/HA/2440",
        "State/ Address": "Gujarat / Ahmedabad",
        "Supplier name": "S.L Trading Company",
        "Total amount": "32,068.49"
    },
    {
        "Consignee address": "S.7, ASHIRA INDUSTRIAL ESTATE, NAROL, AHMEDABAD, GUJARAT, INDIA",
        "Consignee name": "KALAHRUDRA TRENDZ LIMITED",
        "Date of Invoice": "08-08-2023",
        "GST amount": "321548.60",
        "GST rate": "18.00%",
        "GST type": "CGST",
        "GSTIN": "24AAGHG5769P1Z2",
        "Item HSN code": "52081130",
        "Last column to contain control totals for validation": "321548.60",
        "PO reference number": "PO/24/HA/2440",
        "State/ Address": "Gujarat, India",
        "Supplier name": "BIZONGO TECHNOLOGIES PRIVATE LIMITED",
        "Total amount": "321548.60"
    },
    {
        "Consignee address ": "Sector 18, 90B, Delhi, Delhi Expwy Gurgaon 122001 Haryana India",
        "Consignee name": "Smartpaddle Technology Private Limited",
        "Date of Invoice": "2023-08-08",
        "GST amount": "334710.40",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "06AAGCA5045D1Z4",
        "Item HSN code": "---",
        "Last column to contain control totals for validation": "---",
        "PO reference number ": "GPJHA240007288",
        "State/ Address": "Delhi",
        "Supplier name": "Kalahridhaan Trendz Limited",
        "Total amount": "334710.40"
    },
    {
        "Consignee address": "PLOT NO.4N 1/2/3 UPSIDC LITRAMPUR NAGLA GAZIABAD, UTTAR PRADESH, INDIA",
        "Consignee name": "SHRI RATHI Steels Limited",
        "Date of Invoice": "16-08-2023",
        "GST amount": "221328.80",
        "GST rate": "18.00%",
        "GST type": "-",
        "GSTIN": "09AAGCS545L1Z0",
        "Item HSN code": "72201090",
        "Last column to contain control totals for validation": "-",
        "PO reference number": "PO/24/HA/2534",
        "State/ Address": "Uttar Pradesh, India",
        "Supplier name": "Sumit Alloys Private Limited",
        "Total amount": "2272138.76"
    },
  
    {
        "Consignee address": "At Post: Lonand, Tal: Haveli, Dist: Pune-412105 Maharashtra",
        "Consignee name": "Aprn Enterprises Private Limited",
        "Date of Invoice": "9-Sep-2023",
        "GST amount": "2,38,343.09",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "27AABCH8691N1Z",
        "Item HSN code": "76071991",
        "Last column to contain control totals for validation": "3,88,906.75",
        "PO reference number": "PO/PO/24/M/2630",
        "State/ Address": "Maharashtra",
        "Supplier name": "Greenberry Foils India Limited",
        "Total amount": "15,62,471.00"
    },
    {
        "Consignee address": "GREENBURY FOILS INDIA LIMITED\nPLOT NO.101, INDUSTRIAL ESTATE, MORVAI H.A.L, ANGLESHWAR\nBHARUCH, KHARACHIA - 393135",
        "Consignee name": "GREENBURY FOILS INDIA LIMITED",
        "Date of Invoice": "09-09-2023",
        "GST amount": "278.5",
        "GST rate": "18.00%",
        "GST type": "CGST",
        "GSTIN": "24AABCB42012E1Z5",
        "Item HSN code": "76071991",
        "Last column to contain control totals for validation": "144597.20",
        "PO reference number": "PO/24/MHR/26/30",
        "State/ Address": "Maharashtra",
        "Supplier name": "APRN ENTERPRISES PRIVATE LIMITED",
        "Total amount": "144597.20"
    },
    {
        "Consignee address": "KHASRA NO.219/299, GROUND FLOOR, VILLAGE BAMKOLI, LANDMARK: PALM GREEN FARM NEW DELHI - 110036",
        "Consignee name": "---",
        "Date of Invoice": "2023-09-12",
        "GST amount": "3506.00",
        "GST rate": "18.00",
        "GST type": "CGST",
        "GSTIN": "07AAGFS4242L1Z6",
        "Item HSN code": "---",
        "Last column to contain control totals for validation": "---",
        "PO reference number ": "PO/24/9/2021",
        "State/ Address": "---",
        "Supplier name": "OSHO TRADE SERVICES LLP",
        "Total amount": "25597.70"
    },
    {
        "Consignee address": "M/s.Everest Industries Ltd, Plot No. 189/8, UPSIDC Industrial Area, Site V, Kasna, Greater Noida, Distt. Gautam Budh Nagar, Uttar Pradesh, India",
        "Consignee name": "Everest Industries Limited",
        "Date of Invoice": "12-09-2023",
        "GST amount": "41981.50",
        "GST rate": "18.00%",
        "GST type": "CGST",
        "GSTIN": "09AAPCR5322B1Z4",
        "Item HSN code": "39011010",
        "Last column to contain control totals for validation": "83508.28",
        "PO reference number": "PO/24/HA/2931",
        "State/ Address": "Uttar Pradesh, India",
        "Supplier name": "Bizongo India",
        "Total amount": "183486.46"
    },
    {
        "Consignee address": "KHAIRA NO-21 (2F), GROUND FLOOR, VILLAGE BAKOLI, LANDMARK: PALMGREEN FARM NEW DELHI - 110034",
        "Consignee name": "PACKING INDIA",
        "Date of Invoice": "September 12, 2023",
        "GST amount": "2398.50",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "09GSTN783971312M",
        "Item HSN code": "39019010",
        "Last column to contain control totals for validation": "39019010002  -  114.18",
        "PO reference number": "PO Number: 221",
        "State/ Address": "Delhi",
        "Supplier name": "SMARTPADDE TECHNOLOGY PVT. LTD.",
        "Total amount": "13660.00"
    },
    {
        "Consignee address ": "STREET ADDRESS, CITY, STATE, ZIP",
        "Consignee name": "VST VARNS PRIVATE LIMITED",
        "Date of Invoice": "29-09-2023",
        "GST amount": "2985.58",
        "GST rate": "18.00%",
        "GST type": "CGST",
        "GSTIN": "06AAHCU2975B1Z6",
        "Item HSN code": "39219026",
        "Last column to contain control totals for validation": "2985.58",
        "PO reference number ": "PO/24/HA/3151",
        "State/ Address": "HARYANA",
        "Supplier name": "RAJEEV TRADERS",
        "Total amount": "29177.97"
    },
    {
        "Consignee address ": "SADA SHIV CO.OP. TRANSPORT SOCIETY",
        "Consignee name": "---",
        "Date of Invoice": "23-10-2022",
        "GST amount": "90400",
        "GST rate": "18%",
        "GST type": "CGST",
        "GSTIN": "06DSQPP03L1ZB",
        "Item HSN code": "---",
        "Last column to contain control totals for validation": "---",
        "PO reference number ": "AP0/23-24/188",
        "State/ Address": "Haryana",
        "Supplier name": "SMARTPADETECH PRIVATE LIMITED",
        "Total amount": "537884.76"
    },
    {
        "Consignee address": "10A/ABC/V92/101\nShahpur Colony Sector 10D\nGhaziabad, 201002",
        "Consignee name": "Sp Global Commodities Limited",
        "Date of Invoice": "13-Oct-2022",
        "GST amount": "28,27,200.00",
        "GST rate": "18.00",
        "GST type": "CGST",
        "GSTIN": "09ADVPPH1423L2T",
        "Item HSN code": "07133100",
        "Last column to contain control totals for validation": "28,27,200.00",
        "PO reference number": "PO/24A3347",
        "State/ Address": "Uttar Pradesh",
        "Supplier name": "Royal Enterprises",
        "Total amount": "28,27,200.00"
    },
    {
        "Consignee address ": "Sgr global commmodities limited\nHALMAR COLD STORAGE,\nVILLAGE: SAIDPUR PARTAPUR MEERUT,\nDISTT:\nUTTAR PRADESH, INDIA",
        "Consignee name": "Sgr global commmodities limited",
        "Date of Invoice": "13-10-2023",
        "GST amount": "114",
        "GST rate": "5%",
        "GST type": "CGST",
        "GSTIN": "09A0MOVPV12D1ZT",
        "Item HSN code": "07131000",
        "Last column to contain control totals for validation": "114",
        "PO reference number ": "PO/24/HA/3347",
        "State/ Address": "Uttar Pradesh, India",
        "Supplier name": "Royal Enterprises",
        "Total amount": "1140000.00"
    },
    {
        "Consignee address ": "Gala no 04, Kriston House, Sakri Vihar Rd., Sakinaka, Andheri (E), Mumbai, Maharashtra, 400072",
        "Consignee name": "SMARTPADE TECHNOLOGY",
        "Date of Invoice": "26/10/2023",
        "GST amount": "1464.22",
        "GST rate": "18.0",
        "GST type": "CGST",
        "GSTIN": "27AAAVC6045D120",
        "Item HSN code": "63021090",
        "Last column to contain control totals for validation": "0.40",
        "PO reference number ": "D-130, Section 63, Gautam Budh Nagar, Noida-201301, Uttar Pradesh, India",
        "State/ Address": "Maharashtra",
        "Supplier name": "VENUS TEXTILES",
        "Total amount": "34864.80"
    },
    {
        "Consignee address ": "Smartpaddle Technology Private Limited, Bhosari, HQ, Krishna House, 3rd Floor, Off Saki Vihar Road, Saki Naka, Andheri East Mumbai 400072 Maharashtra India",
        "Consignee name": "Smartpaddle Technology Private Limited",
        "Date of Invoice": "28-10-2022",
        "GST amount": "1552254.4800",
        "GST rate": "18.00",
        "GST type": "CGST",
        "GSTIN": "27AAGCB46D120",
        "Item HSN code": "9403891149",
        "Last column to contain control totals for validation": "17520",
        "PO reference number ": "POAR026",
        "State/ Address": "Uttar Pradesh",
        "Supplier name": "Aaroka Fashion Private Limited",
        "Total amount": "8622400.9600"
    },
    {
        "Consignee address ": "Khasra no 1740 THANA MOREPEN ROAD BADDI, Solan, Himachal Pradesh, 173205",
        "Consignee name": "SMARTPADDLE TECHNOLOGY PRIVATE LIMITED",
        "Date of Invoice": "31-08-2023",
        "GST amount": "60177.60",
        "GST rate": "18%",
        "GST type": "IGST",
        "GSTIN": "02AACV650124",
        "Item HSN code": "72101290",
        "Last column to contain control totals for validation": "60177.60",
        "PO reference number ": "000000",
        "State/ Address": "Himachal Pradesh",
        "Supplier name": "SURBHI PACKERS",
        "Total amount": "334320.00"
    },
    {
        "Consignee address ": "Sector 18, 908, Delhi, Jaipur Expwy Gurgaon 122001 Haryana India",
        "Consignee name": "Smartpaddle Technology Private Limited",
        "Date of Invoice": "2023-11-05",
        "GST amount": "40078.00",
        "GST rate": "18.00",
        "GST type": "CGST",
        "GSTIN": "02AAFC52395E1Z5",
        "Item HSN code": "---",
        "Last column to contain control totals for validation": "---",
        "PO reference number ": "B2PO-21352-266109",
        "State/ Address": "Haryana",
        "Supplier name": "SAGAR ISPAT INDIA PRIVATE LIMITED",
        "Total amount": "2404531.24"
    }
]

# export_to_csv(data, 'output.csv')            